version: '1'
services:
  abctelecome:
    image: 'shoaibpki/abctelecom'
    container_name: abctelecom
    ports:
      - '8082:8082'
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: 'mysql:8.0.31'
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=abctelecom
      - MYSQL_ROOT_PASSWORD=root
