spring:
  application:
    name: "ABC-TELECOM"
  datasource:
    url: jdb:mysql://localhost:3306/abctelecom?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



